
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const LeadChannel = {
  WEBSITE: 'WEBSITE',
  ADSENSE: 'ADSENSE',
  WHATSAPP: 'WHATSAPP',
  INSTAGRAM: 'INSTAGRAM',
  FACEBOOK: 'FACEBOOK',
  REFERRAL: 'REFERRAL',
  OTHER: 'OTHER'
} as const

export type LeadChannel = (typeof LeadChannel)[keyof typeof LeadChannel]


export const LeadStatus = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUALIFIED: 'QUALIFIED',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST'
} as const

export type LeadStatus = (typeof LeadStatus)[keyof typeof LeadStatus]


export const MediaKind = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT'
} as const

export type MediaKind = (typeof MediaKind)[keyof typeof MediaKind]
